# Generated by Django 5.0.1 on 2024-02-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', to_field='employee_code'),
        ),
    ]
