# Generated by Django 5.0.1 on 2024-02-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_employee_code'),
        ('employee', '0002_remove_employee_id_alter_employee_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
