# Generated by Django 5.0.1 on 2024-02-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_employee_code'),
        ('employee', '0002_remove_employee_id_alter_employee_employee_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee_code', 'date', 'punch_time')},
        ),
    ]
