# Generated by Django 5.0.1 on 2024-02-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_unique_together_and_more'),
        ('employee', '0002_remove_employee_id_alter_employee_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_punch_time', models.DateTimeField()),
                ('last_punch_time', models.DateTimeField()),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
